// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9wl6ij3IlWYdbU9Bcybh1VOIIoLLpmxQ',
    appId: '1:291300004164:web:5a8c567614750b2b164711',
    messagingSenderId: '291300004164',
    projectId: 'notesapp-ba0e0',
    authDomain: 'notesapp-ba0e0.firebaseapp.com',
    storageBucket: 'notesapp-ba0e0.appspot.com',
    measurementId: 'G-7ZP7FD05B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALXym9Y4fK-ss9gZiGrezPxmiwFP848e0',
    appId: '1:291300004164:android:cb7cce3e9a188640164711',
    messagingSenderId: '291300004164',
    projectId: 'notesapp-ba0e0',
    storageBucket: 'notesapp-ba0e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy41tBJzc733nhZ-RjN1Z_auNImix67iI',
    appId: '1:291300004164:ios:b63c487ebca2916b164711',
    messagingSenderId: '291300004164',
    projectId: 'notesapp-ba0e0',
    storageBucket: 'notesapp-ba0e0.appspot.com',
    iosBundleId: 'com.example.googleKeepNoteClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy41tBJzc733nhZ-RjN1Z_auNImix67iI',
    appId: '1:291300004164:ios:9b1e939d04876d17164711',
    messagingSenderId: '291300004164',
    projectId: 'notesapp-ba0e0',
    storageBucket: 'notesapp-ba0e0.appspot.com',
    iosBundleId: 'com.example.googleKeepNoteClone.RunnerTests',
  );
}
